# Generated by Django 4.2.7 on 2023-11-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Bid', 'Bid'), ('Code', 'Code')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('leader_name', models.CharField(max_length=100)),
                ('leader_email', models.EmailField(max_length=254, unique=True)),
                ('profile_photo_url', models.URLField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('team_member_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_2', to='auth_g.team_member')),
                ('team_member_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_3', to='auth_g.team_member')),
                ('team_member_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_4', to='auth_g.team_member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
