# Generated by Django 4.2.7 on 2023-11-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_g', '0003_remove_user_username_user_google_oauth_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
