# Generated by Django 4.2.7 on 2023-11-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_g', '0004_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Bid', 'Bid'), ('Code', 'Code')], max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_oauth_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='leader_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_member_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_2', to='auth_g.teammember'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_member_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_3', to='auth_g.teammember'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_member_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_4', to='auth_g.teammember'),
        ),
        migrations.DeleteModel(
            name='team_member',
        ),
    ]
