# Generated by Django 4.2.7 on 2023-11-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_g', '0006_team_member_user_google_oauth_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
