# Generated by Django 4.2.7 on 2023-11-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_g', '0007_remove_user_username_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
