# Generated by Django 4.2.7 on 2023-11-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_g', '0008_alter_user_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teammember1_name', models.CharField(max_length=100)),
                ('teammember1_email', models.EmailField(max_length=254, unique=True)),
                ('role1', models.CharField(choices=[('Bid', 'Bid'), ('Code', 'Code')], default='Bid', max_length=10)),
                ('teammember2_name', models.CharField(max_length=100)),
                ('teammember2_email', models.EmailField(max_length=254, unique=True)),
                ('role2', models.CharField(choices=[('Bid', 'Bid'), ('Code', 'Code')], default='Bid', max_length=10)),
                ('teammember3_name', models.CharField(max_length=100)),
                ('teammember3_email', models.EmailField(max_length=254, unique=True)),
                ('role3', models.CharField(choices=[('Bid', 'Bid'), ('Code', 'Code')], default='Bid', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_member_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_member_3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_member_4',
        ),
        migrations.DeleteModel(
            name='team_member',
        ),
        migrations.AddField(
            model_name='team_members',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_g.user'),
        ),
    ]
