# Generated by Django 4.2.7 on 2023-11-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_g', '0010_alter_team_members_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_members',
            name='leader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_g.user'),
        ),
    ]
