# Generated by Django 4.2.7 on 2023-11-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_g', '0012_alter_team_members_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_members',
            name='id',
        ),
        migrations.AlterField(
            model_name='team_members',
            name='leader',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
