# Generated by Django 4.2.7 on 2023-11-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_g', '0014_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='receipt',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
